Repository BTH-StoraSpel-DXR/SPLASH, pull requests merged in 2019-12, with the labels that each got.

#659 U675/T680 final KillCam data
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/KeyBinds.cpp
  Sail/src/Sail/KeyBinds.h
  Sail/src/Sail/entities/systems/network/receivers/KillCamReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/KillCamReceiverSystem.h
Labels: currently merging

#663 Added cleaning bot and all required textures
  SPLASH/res/models/CleaningBot.fbx
  SPLASH/res/textures/pbr/DDS/CleaningRobot/CleaningBot_Albedo.dds
  SPLASH/res/textures/pbr/DDS/CleaningRobot/CleaningBot_MRAO.dds
  SPLASH/res/textures/pbr/DDS/CleaningRobot/CleaningBot_NM.dds
  SPLASH/src/game/states/SplashScreenState.cpp
Labels: needs testing

#661 Hf/audio slider connected to volume
  SPLASH/src/game/states/GameState.cpp
  Sail/src/API/Audio/AudioEngine.cpp
  Sail/src/Sail/entities/systems/Audio/AudioSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/SanitySoundSystem.cpp
  Sail/src/Sail/utils/SailImGui/OptionsWindow.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: currently merging

#655 Clients can now select their own team color
  SPLASH/src/game/states/LobbyState.cpp
  SPLASH/src/game/states/LobbyState.h
  Sail/src/Network/NWrapper.h
  Sail/src/Network/NWrapperClient.cpp
  Sail/src/Network/NWrapperClient.h
  Sail/src/Network/NWrapperHost.cpp
  Sail/src/Network/NWrapperHost.h
  Sail/src/Sail/events/Event.h
  Sail/src/Sail/events/types/NetworkTeamColorRequest.h
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: currently merging

#667 Added spawnpoints for powerups in corridors
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.h
Labels: currently merging

#669 Hf/ai maintenance
  Physics/Intersection.cpp
  Physics/Intersection.h
  Physics/Octree.cpp
  Physics/Octree.h
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/GameState.h
  Sail/src/Sail/ai/pathfinding/NodeSystem.cpp
  Sail/src/Sail/ai/pathfinding/NodeSystem.h
  Sail/src/Sail/ai/states/SearchingState.cpp
  Sail/src/Sail/ai/states/SearchingState.h
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/EntityFactory.hpp
  Sail/src/Sail/entities/systems/Gameplay/ai/AiSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/ai/AiSystem.h
  Sail/src/Sail/entities/systems/SystemDeclarations.h
  Sail/src/Sail/entities/systems/Systems.h
  Sail/src/Sail/netcode/NetworkedStructs.cpp
  Sail/src/Sail/netcode/NetworkedStructs.h
  Sail/src/Sail/utils/SailImGui/Profiler.cpp
Labels: currently merging

#668 U675/T681 Final KillCam Logic
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/GameState.h
  Sail/src/Sail/entities/systems/Gameplay/PlayerSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.h
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/KillCamReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/KillCamReceiverSystem.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystemHost.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystemHost.h
  Sail/src/Sail/entities/systems/network/receivers/ReceiverBase.cpp
  Sail/src/Sail/entities/systems/network/receivers/ReceiverBase.h
  Sail/src/Sail/events/Event.h
  Sail/src/Sail/events/Events.h
  Sail/src/Sail/events/types/PlayerDiedEvent.h
  Sail/src/Sail/events/types/StartKillCamEvent.h
  Sail/src/Sail/events/types/StopKillCamEvent.h
  Sail/src/Sail/events/types/ToggleKillCamEvent.h
  Sail/src/Sail/netcode/NetworkedStructs.h
Labels: currently merging

#671 removed bots from debug
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/ai/pathfinding/NodeSystem.cpp
Labels: hotfix, needs code review, needs testing

#662 U674/t689 compile shader once
  SPLASH/res/shaders/compute/ParticleComputeShader.hlsl
  SPLASH/res/textures/particles/animSmoke.dds
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/api/shader/ShaderPipeline.cpp
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/components/ParticleEmitterComponent.cpp
  Sail/src/Sail/entities/components/ParticleEmitterComponent.h
  Sail/src/Sail/entities/components/SpotlightComponent.h
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/SprinklerSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/SprinklerSystem.h
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.cpp
  Sail/src/Sail/entities/systems/Graphics/ParticleSystem.cpp
  Sail/src/Sail/entities/systems/Graphics/ParticleSystem.h
  Sail/src/Sail/entities/systems/SystemDeclarations.h
  Sail/src/Sail/entities/systems/Systems.h
  Sail/src/Sail/entities/systems/light/HazardLightSystem.cpp
  Sail/src/Sail/entities/systems/light/HazardLightSystem.h
Labels: currently merging

#679 Added logic for sprinklers, particles and hazard lights
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/components/ParticleEmitterComponent.cpp
  Sail/src/Sail/entities/components/ParticleEmitterComponent.h
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.cpp
  Sail/src/Sail/entities/systems/light/HazardLightSystem.cpp
Labels: currently merging

#676 Issues/636 performance test sound not working
  Sail/src/API/Audio/AudioEngine.cpp
  Sail/src/API/Audio/AudioEngine.h
Labels: currently merging

#684 Polish/Kill Cam
  SPLASH/src/Main.cpp
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/GameState.h
  SPLASH/src/game/states/PBRTestState.cpp
  Sail/src/Sail/TimeSettings.h
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/EntityFactory.hpp
  Sail/src/Sail/entities/components/ReplayReceiverComponent.h
  Sail/src/Sail/entities/systems/Gameplay/GunSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/ProjectileSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/ai/AiSystem.cpp
  Sail/src/Sail/entities/systems/SystemDeclarations.h
  Sail/src/Sail/entities/systems/input/GameInputSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/KillCamReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/KillCamReceiverSystem.h
  Sail/src/Sail/entities/systems/physics/CollisionSystem.cpp
  Sail/src/Sail/entities/systems/physics/CollisionSystem.h
  Sail/src/Sail/entities/systems/physics/OctreeAddRemoverSystem.cpp
  Sail/src/Sail/entities/systems/physics/OctreeAddRemoverSystem.h
Labels: currently merging

#683 Player Names
  Physics/Octree.cpp
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/GameState.h
  Sail/src/Sail.h
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/utils/SailImGui/PlayerNamesImGui.cpp
  Sail/src/Sail/utils/SailImGui/PlayerNamesImGui.h
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.h
  Sail/src/Sail/utils/Utils.cpp
  Sail/src/Sail/utils/Utils.h
Labels: needs testing

#675 U541/t684 softshadow texture optimization
  SPLASH/res/shaders/dxr/Basic.hlsl
  SPLASH/res/shaders/dxr/Common_hlsl_cpp.hlsl
  SPLASH/res/shaders/dxr/shading/ShadePass.hlsl
  Sail/src/API/DX12/dxr/DXRBase.cpp
  Sail/src/API/DX12/dxr/DXRBase.h
  Sail/src/API/DX12/renderer/DX12RaytracingRenderer.cpp
  Sail/src/API/DX12/renderer/DX12RaytracingRenderer.h
  Sail/src/API/DX12/resources/DX12RenderableTexture.cpp
  Sail/src/Sail/api/Texture.h
Labels: currently merging

#687 U538/t679 hud indicator for power ups
  Sail/src/Sail/utils/SailImGui/InGameGui.cpp
Labels: needs testing

#688 HF/InstantModelLoading
  SPLASH/res/models/CleaningBot.notfbx
  SPLASH/res/models/Clutter/Books1.notfbx
  SPLASH/res/models/Clutter/Boxes.notfbx
  SPLASH/res/models/Clutter/CloningVats.notfbx
  SPLASH/res/models/Clutter/ControlStation.notfbx
  SPLASH/res/models/Clutter/MediumBox.notfbx
  SPLASH/res/models/Clutter/Microscope.notfbx
  SPLASH/res/models/Clutter/Notepad.notfbx
  SPLASH/res/models/Clutter/PowerUp.notfbx
  SPLASH/res/models/Clutter/Saftblandare.notfbx
  SPLASH/res/models/Clutter/Screen.notfbx
  SPLASH/res/models/Clutter/SquareBox.notfbx
  SPLASH/res/models/Clutter/Table.notfbx
  SPLASH/res/models/Doc.notfbx
  SPLASH/res/models/Tiles/CorridorCorner.notfbx
  SPLASH/res/models/Tiles/CorridorDoor.notfbx
  SPLASH/res/models/Tiles/CorridorWall.notfbx
  SPLASH/res/models/Tiles/RoomCeiling.notfbx
  SPLASH/res/models/Tiles/RoomCorner.notfbx
  SPLASH/res/models/Tiles/RoomDoor.notfbx
  SPLASH/res/models/Tiles/RoomFloor.notfbx
  SPLASH/res/models/Tiles/RoomWall.notfbx
  SPLASH/res/models/Torch.notfbx
  SPLASH/res/models/WaterPistol.notfbx
  SPLASH/res/models/boundingBox.notfbx
  SPLASH/res/models/candleExported.notfbx
  SPLASH/res/models/cubeWidth1.notfbx
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/MenuState.cpp
  SPLASH/src/game/states/PBRTestState.cpp
  SPLASH/src/game/states/SplashScreenState.cpp
  Sail/src/Sail/ai/pathfinding/NodeSystem.cpp
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/systems/Graphics/AnimationSystem.cpp
  Sail/src/Sail/graphics/geometry/Animation.cpp
  Sail/src/Sail/graphics/geometry/Animation.h
  Sail/src/Sail/resources/ResourceManager.cpp
  Sail/src/Sail/resources/ResourceManager.h
  Sail/src/Sail/resources/loaders/NotFBXLoader.cpp
  Sail/src/Sail/resources/loaders/NotFBXLoader.h
Labels: approved, currently merging, hotfix

#689 fixed bots spawning on players, limited map size and map random size
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/api/ImGuiHandler.cpp
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.h
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.cpp
  Sail/src/Sail/entities/systems/render/BeginEndFrameSystem.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: currently merging

#695 VRAM reduction again
  SPLASH/res/shaders/dxr/Basic.hlsl
  SPLASH/res/shaders/dxr/Common_hlsl_cpp.hlsl
  SPLASH/res/shaders/dxr/Utils.hlsl
  SPLASH/res/shaders/postprocess/GaussianBlurHorizontal.hlsl
  SPLASH/res/shaders/postprocess/Tonemapper.hlsl
  Sail/src/API/DX12/dxr/DXRBase.cpp
  Sail/src/API/DX12/dxr/DXRBase.h
  Sail/src/API/DX12/dxr/DXRUtils.cpp
  Sail/src/API/DX12/dxr/DXRUtils.h
  Sail/src/API/DX12/renderer/DX12ForwardRenderer.cpp
  Sail/src/API/DX12/renderer/DX12RaytracingRenderer.cpp
  Sail/src/Sail/graphics/postprocessing/PostProcessPipeline.cpp
  Sail/src/Sail/graphics/postprocessing/PostProcessPipeline.h
  Sail/src/Sail/graphics/shader/postprocess/GaussianBlurHorizontal.cpp
  Sail/src/Sail/graphics/shader/postprocess/GaussianBlurHorizontal.h
  Sail/src/Sail/graphics/shader/postprocess/TonemapShader.cpp
  Sail/src/Sail/utils/SailImGui/OptionsWindow.cpp
Labels: currently merging, needs testing

#696 Compressed network packets
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/entities/systems/network/HostSendToSpectatorSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/ReceiverBase.cpp
  Sail/src/Sail/graphics/shader/postprocess/GaussianBlurVertical.cpp
  Sail/src/Sail/netcode/NetworkedStructs.h
  Sail/src/Sail/utils/SailImGui/PlayerNamesImGui.cpp
  Sail/src/Sail/utils/SailImGui/Profiler.cpp
  libraries/gzip/compress.hpp
  libraries/gzip/config.hpp
  libraries/gzip/decompress.hpp
  libraries/gzip/utils.hpp
  libraries/gzip/version.hpp
  libraries/zlib/zconf.h
  libraries/zlib/zlib.h
  libraries/zlib/zlibstatic.lib
  premake5.lua
Labels: currently merging, needs testing

#694 H3nx/credits
  SPLASH/src/game/states/MenuState.cpp
  SPLASH/src/game/states/MenuState.h
  Sail/src/Sail/utils/SailImGui/SailImGui.cpp
  Sail/src/Sail/utils/SailImGui/SailImGui.h
Labels: approved, currently merging, documentation, enHANSement

#664 Record match
  .gitignore
  SPLASH/replays/README.txt
  SPLASH/replays/temp/README.txt
  SPLASH/src/game/states/EndGameState.cpp
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/LobbyHostState.cpp
  SPLASH/src/game/states/LobbyState.cpp
  SPLASH/src/game/states/LobbyState.h
  SPLASH/src/game/states/MenuState.cpp
  SPLASH/src/game/states/MenuState.h
  Sail/src/Network/NWrapper.h
  Sail/src/Network/NWrapperHost.cpp
  Sail/src/Network/NWrapperHost.h
  Sail/src/Network/NWrapperSingleton.cpp
  Sail/src/Network/NWrapperSingleton.h
  Sail/src/Network/NetworkModule.cpp
  Sail/src/Network/NetworkModule.hpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.h
  Sail/src/Sail/entities/systems/network/receivers/MatchRecordSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/MatchRecordSystem.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.h
  Sail/src/Sail/entities/systems/network/receivers/ReceiverBase.cpp
  Sail/src/Sail/utils/SailImGui/OptionsWindow.cpp
  Sail/src/Sail/utils/SailImGui/OptionsWindow.h
  Sail/src/Sail/utils/SailImGui/WaitingForPlayersWindow.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: currently merging

#699 Hf/player name fade delay
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/utils/SailImGui/PlayerNamesImGui.cpp
  Sail/src/Sail/utils/SailImGui/PlayerNamesImGui.h
Labels: currently merging

#698 Hf/fullscreen option
  Sail/src/API/DX12/DX12API.cpp
  Sail/src/API/DX12/DX12API.h
  Sail/src/API/DX12/dxr/DXRBase.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: needs testing
