Repository BTH-StoraSpel-DXR/SPLASH, pull requests merged in 2019-11, with the labels that each got.

#423 Maintenance/QoLAgain ヽ༼ຈل͜ຈ༽ﾉ
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/MenuState.cpp
  Sail/src/Sail/entities/ECS.cpp
  Sail/src/Sail/entities/ECS.h
  Sail/src/Sail/entities/Entity.cpp
  Sail/src/Sail/entities/Entity.h
  Sail/src/Sail/entities/components/AnimationComponent.h
  Sail/src/Sail/entities/components/AudioComponent.h
  Sail/src/Sail/entities/components/BoundingBoxComponent.h
  Sail/src/Sail/entities/components/CollidableComponent.h
  Sail/src/Sail/entities/components/CollisionComponent.h
  Sail/src/Sail/entities/components/Component.cpp
  Sail/src/Sail/entities/components/Component.h
  Sail/src/Sail/entities/components/CullingComponent.h
  Sail/src/Sail/entities/components/GunComponent.h
  Sail/src/Sail/entities/components/LightComponent.h
  Sail/src/Sail/entities/components/ModelComponent.h
  Sail/src/Sail/entities/components/MovementComponent.h
  Sail/src/Sail/entities/components/NetworkReceiverComponent.h
  Sail/src/Sail/entities/components/NetworkSenderComponent.h
  Sail/src/Sail/entities/components/OnlineOwnerComponent.h
  Sail/src/Sail/entities/components/SpeedLimitComponent.h
  Sail/src/Sail/entities/components/TransformComponent.h
  Sail/src/Sail/entities/systems/BaseComponentSystem.cpp
  Sail/src/Sail/entities/systems/BaseComponentSystem.h
  Sail/src/Sail/entities/systems/Gameplay/GunSystem.h
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.h
  Sail/src/Sail/entities/systems/physics/OctreeAddRemoverSystem.h
  Sail/src/Sail/entities/systems/render/BoundingboxSubmitSystem.h
  Sail/src/Sail/entities/systems/render/ImGui/RenderImGuiSystem.cpp
  Sail/src/Sail/entities/systems/render/ImGui/RenderImGuiSystem.h
  Sail/src/Sail/utils/SailImGui/ECS_SystemInfoImGuiWindow.cpp
Labels: enhancement, help wanted, maintenance

#429 HF/Prevent WATER_HIT_PLAYER spam
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Network/NWrapperSingleton.cpp
  Sail/src/Network/NWrapperSingleton.h
  Sail/src/Network/NetworkModule.cpp
  Sail/src/Network/NetworkModule.hpp
  Sail/src/Sail/entities/components/CandleComponent.h
  Sail/src/Sail/entities/systems/Gameplay/ProjectileSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.cpp
  Sail/src/Sail/entities/systems/input/GameInputSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/utils/SailImGui/Profiler.cpp
  Sail/src/Sail/utils/SailImGui/Profiler.h
Labels: currently merging

#435 Hf/427 duplicate vertex buffers
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/PBRTestState.cpp
  Sail/src/Sail/Application.cpp
  Sail/src/Sail/TimeSettings.h
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/systems/SystemDeclarations.h
  Sail/src/Sail/entities/systems/Systems.h
  Sail/src/Sail/entities/systems/input/GameInputSystem.cpp
  Sail/src/Sail/entities/systems/render/ModelSubmitSystem.cpp
  Sail/src/Sail/entities/systems/render/RealTimeModelSubmitSystem.cpp
  Sail/src/Sail/entities/systems/render/RealTimeModelSubmitSystem.h
Labels: currently merging

#446 U594/T595T596 torch and gun network components
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Network/NWrapperSingleton.cpp
  Sail/src/Sail/TimeSettings.h
  Sail/src/Sail/entities/Entity.cpp
  Sail/src/Sail/entities/Entity.h
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/EntityFactory.hpp
  Sail/src/Sail/entities/components/NetworkSenderComponent.h
  Sail/src/Sail/entities/systems/Gameplay/candles/CandlePlacementSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.h
  Sail/src/Sail/graphics/geometry/Transform.cpp
  Sail/src/Sail/graphics/geometry/Transform.h
  Sail/src/Sail/netcode/ArchiveHelperFunctions.h
  Sail/src/Sail/netcode/NetworkedStructs.h
  Sail/src/Sail/utils/SailImGui/ECS_SystemInfoImGuiWindow.cpp
Labels: currently merging

#448 U524/t564 sprinkler system
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/entities/components/MapComponent.h
  Sail/src/Sail/entities/components/SpotlightComponent.h
  Sail/src/Sail/entities/systems/Gameplay/LevelGeneratorSystem/LevelGeneratorSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/SprinklerSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/SprinklerSystem.h
  Sail/src/Sail/entities/systems/SystemDeclarations.h
  Sail/src/Sail/entities/systems/Systems.h
  Sail/src/Sail/entities/systems/light/SpotLightSystem.cpp
  Sail/src/Sail/entities/systems/light/SpotLightSystem.h
Labels: currently merging

#443 U397/t612 settings & Maintenance
  .gitignore
  SPLASH/res/data/settings.saildata
  SPLASH/src/game/Game.cpp
  SPLASH/src/game/events/SettingsEvent.h
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/LobbyClientState.cpp
  SPLASH/src/game/states/LobbyClientState.h
  SPLASH/src/game/states/LobbyState.cpp
  SPLASH/src/game/states/LobbyState.h
  SPLASH/src/game/states/MenuState.cpp
  SPLASH/src/game/states/MenuState.h
  SPLASH/src/game/states/SplashScreenState.cpp
  SPLASH/src/game/states/SplashScreenState.h
  Sail/src/API/DX12/dxr/DXRBase.cpp
  Sail/src/API/DX12/renderer/DX12RaytracingRenderer.cpp
  Sail/src/Network/NWrapperClient.cpp
  Sail/src/Sail/Application.cpp
  Sail/src/Sail/Application.h
  Sail/src/Sail/entities/components/MapComponent.h
  Sail/src/Sail/entities/systems/Gameplay/LevelGeneratorSystem/LevelGeneratorSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.h
  Sail/src/Sail/entities/systems/Gameplay/SprinklerSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/SprinklerSystem.h
  Sail/src/Sail/entities/systems/SystemDeclarations.h
  Sail/src/Sail/entities/systems/Systems.h
  Sail/src/Sail/entities/systems/input/GameInputSystem.cpp
  Sail/src/Sail/entities/systems/input/GameInputSystem.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/events/Event.h
  Sail/src/Sail/resources/ResourceManager.cpp
  Sail/src/Sail/resources/ResourceManager.h
  Sail/src/Sail/resources/loaders/FBXLoader.cpp
  Sail/src/Sail/resources/loaders/FBXLoader.h
  Sail/src/Sail/states/StateIdentifiers.h
  Sail/src/Sail/utils/Regex/Regex.h
  Sail/src/Sail/utils/SailImGui/ConsoleCommands.cpp
  Sail/src/Sail/utils/SailImGui/ConsoleCommands.h
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.h
Labels: currently merging

#470 HF/host authority
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/components/CandleComponent.h
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandlePlacementSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleReignitionSystem.cpp
  Sail/src/Sail/entities/systems/input/SprintingSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystemClient.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystemHost.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystemHost.h
  Sail/src/Sail/netcode/NetworkedStructs.h
  Sail/src/Sail/utils/SailImGui/ConsoleCommands.h
Labels: currently merging

#467 U532/t555 dispatcher in network receiver
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/GameState.h
  Sail/src/API/Windows/Win32Input.cpp
  Sail/src/API/Windows/Win32Window.cpp
  Sail/src/Network/NWrapperSingleton.cpp
  Sail/src/Network/NWrapperSingleton.h
  Sail/src/Sail/Application.cpp
  Sail/src/Sail/RendererWrapper.cpp
  Sail/src/Sail/api/GraphicsAPI.cpp
  Sail/src/Sail/api/GraphicsAPI.h
  Sail/src/Sail/entities/systems/Audio/AudioSystem.cpp
  Sail/src/Sail/entities/systems/Audio/AudioSystem.h
  Sail/src/Sail/entities/systems/Gameplay/GunSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/GunSystem.h
  Sail/src/Sail/entities/systems/Gameplay/PlayerSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/PlayerSystem.h
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.h
  Sail/src/Sail/entities/systems/Gameplay/candles/CandlePlacementSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandlePlacementSystem.h
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleReignitionSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleReignitionSystem.h
  Sail/src/Sail/entities/systems/SystemDeclarations.h
  Sail/src/Sail/entities/systems/Systems.h
  Sail/src/Sail/entities/systems/input/GameInputSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystemHost.cpp
  Sail/src/Sail/events/Event.h
  Sail/src/Sail/events/Events.h
  Sail/src/Sail/events/PlayerCandleDeathEvent.h
  Sail/src/Sail/events/types/ChangeWalkingSoundEvent.h
  Sail/src/Sail/events/types/HoldingCandleToggleEvent.h
  Sail/src/Sail/events/types/IgniteCandleEvent.h
  Sail/src/Sail/events/types/PlayerDiedEvent.h
  Sail/src/Sail/events/types/PlayerJumpedEvent.h
  Sail/src/Sail/events/types/PlayerLandedEvent.h
  Sail/src/Sail/events/types/StartShootingEvent.h
  Sail/src/Sail/events/types/StopShootingEvent.h
  Sail/src/Sail/events/types/StopWalkingEvent.h
  Sail/src/Sail/events/types/WaterHitPlayerEvent.h
  Sail/src/Sail/events/types/WindowFocusChangedEvent.h
  Sail/src/Sail/events/types/WindowResizeEvent.h
  Sail/src/Sail/netcode/NetworkedStructs.h
  Sail/src/Sail/utils/SailImGui/KillFeedWindow.cpp
  Sail/src/Sail/utils/SailImGui/KillFeedWindow.h
Labels: Needs testing, currently merging

#468 ISSUE: Running Sound Continue After Death
  Sail/src/Sail/entities/systems/input/GameInputSystem.cpp
  Sail/src/Sail/entities/systems/input/GameInputSystem.h
Labels: approved

#474 MT/Added a ImGui window for displaying debug information from the networ…
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/GameState.h
  Sail/src/Network/NWrapperHost.cpp
  Sail/src/Network/NWrapperHost.h
  Sail/src/Sail.h
  Sail/src/Sail/utils/SailImGui/NetworkInfoWindow.cpp
  Sail/src/Sail/utils/SailImGui/NetworkInfoWindow.h
Labels: currently merging

#475 HF/network reorganizing
  SPLASH/src/game/events/NetworkChatEvent.h
  SPLASH/src/game/events/NetworkDisconnectEvent.h
  SPLASH/src/game/events/NetworkJoinedEvent.h
  SPLASH/src/game/states/EndGameState.cpp
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/LobbyClientState.cpp
  SPLASH/src/game/states/LobbyClientState.h
  SPLASH/src/game/states/LobbyHostState.cpp
  SPLASH/src/game/states/LobbyHostState.h
  SPLASH/src/game/states/LobbyState.cpp
  SPLASH/src/game/states/LobbyState.h
  SPLASH/src/game/states/MenuState.cpp
  Sail/src/Network/NWrapper.cpp
  Sail/src/Network/NWrapper.h
  Sail/src/Network/NWrapperClient.cpp
  Sail/src/Network/NWrapperClient.h
  Sail/src/Network/NWrapperHost.cpp
  Sail/src/Network/NWrapperHost.h
  Sail/src/Network/NWrapperSingleton.cpp
  Sail/src/Network/NWrapperSingleton.h
  Sail/src/Network/NetworkModule.cpp
  Sail/src/Network/NetworkModule.hpp
  Sail/src/Network/NetworkStructs.hpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.h
  Sail/src/Sail/netcode/NetworkedStructs.h
  Sail/src/Sail/utils/GameDataTracker.cpp
  Sail/src/Sail/utils/GameDataTracker.h
  Sail/src/Sail/utils/SailImGui/KillFeedWindow.cpp
Labels: currently merging

#480 HF/ Multiple water streams in Performance Test
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/systems/Gameplay/GunSystem.cpp
Labels: currently merging

#482 Issue/no audio output device
  Sail/src/API/Audio/AudioEngine.cpp
  Sail/src/API/Audio/AudioEngine.h
Labels: currently merging

#452 U594/T597 projectile network components
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/EntityFactory.hpp
  Sail/src/Sail/entities/components/LightComponent.h
  Sail/src/Sail/entities/components/NetworkSenderComponent.h
  Sail/src/Sail/entities/components/PlayerComponent.h
  Sail/src/Sail/entities/systems/Gameplay/GunSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/ProjectileSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.cpp
  Sail/src/Sail/entities/systems/input/GameInputSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.h
  Sail/src/Sail/netcode/NetworkedStructs.h
Labels: currently merging

#479 Becoming host as an earlier client makes players fall through the floor upon spawning [FIXED]
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/entities/components/CandleComponent.cpp
  Sail/src/Sail/entities/components/CandleComponent.h
  Sail/src/Sail/entities/systems/Gameplay/GunSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.cpp
  Sail/src/Sail/utils/SailImGui/ECS_SystemInfoImGuiWindow.cpp
  Sail/src/Sail/utils/SailImGui/ECS_SystemInfoImGuiWindow.h
Labels: approved

#504 U144/T593 delay deletion of players
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/entities/Entity.cpp
  Sail/src/Sail/entities/Entity.h
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/EntityFactory.hpp
  Sail/src/Sail/entities/components/Component.h
  Sail/src/Sail/entities/components/NetworkReceiverComponent.h
  Sail/src/Sail/entities/components/ReplayComponent.h
  Sail/src/Sail/entities/systems/Gameplay/PlayerSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
Labels: currently merging

#509 U289/t616 new update particle physics
  SPLASH/res/shaders/compute/ParticleComputeShader.hlsl
  Sail/src/API/DX12/renderer/DX12GBufferRenderer.cpp
  Sail/src/API/DX12/shader/DX12StructuredBuffer.cpp
  Sail/src/Sail/api/shader/ShaderPipeline.cpp
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/components/ParticleEmitterComponent.cpp
  Sail/src/Sail/entities/components/ParticleEmitterComponent.h
  Sail/src/Sail/entities/systems/Graphics/ParticleSystem.cpp
  Sail/src/Sail/entities/systems/Graphics/ParticleSystem.h
  Sail/src/Sail/graphics/shader/compute/ParticleComputeShader.h
Labels: currently merging

#500 U429/t515 water is now shadowed
  SPLASH/res/shaders/dxr/PBR.hlsl
  SPLASH/res/shaders/dxr/Shading.hlsl
Labels: currently merging

#513 U429/t449 water running down walls
  SPLASH/res/shaders/dxr/Shading.hlsl
  Sail/src/API/DX12/dxr/DXRBase.cpp
  Sail/src/API/DX12/dxr/DXRBase.h
  Sail/src/API/DX12/renderer/DX12RaytracingRenderer.cpp
  Sail/src/Sail/utils/SailImGui/OptionsWindow.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: currently merging

#516 HF/more network stuff
  SPLASH/src/game/events/NetworkBackToLobby.h
  SPLASH/src/game/events/NetworkDisconnectEvent.h
  SPLASH/src/game/events/NetworkStartGameEvent.h
  SPLASH/src/game/states/EndGameState.cpp
  SPLASH/src/game/states/EndGameState.h
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/GameState.h
  SPLASH/src/game/states/LobbyClientState.cpp
  SPLASH/src/game/states/LobbyClientState.h
  SPLASH/src/game/states/LobbyState.cpp
  SPLASH/src/game/states/LobbyState.h
  SPLASH/src/game/states/MenuState.cpp
  SPLASH/src/game/states/SplashScreenState.cpp
  SPLASH/src/game/states/SplashScreenState.h
  Sail/src/Network/NWrapper.cpp
  Sail/src/Network/NWrapper.h
  Sail/src/Network/NWrapperClient.cpp
  Sail/src/Network/NWrapperClient.h
  Sail/src/Network/NWrapperHost.cpp
  Sail/src/Network/NWrapperHost.h
  Sail/src/Network/NWrapperSingleton.cpp
  Sail/src/Network/NWrapperSingleton.h
  Sail/src/Network/NetworkModule.cpp
  Sail/src/Network/NetworkModule.hpp
  Sail/src/Sail.h
  Sail/src/Sail/events/Event.h
  Sail/src/Sail/events/types/NetworkChangeStateEvent.h
  Sail/src/Sail/events/types/NetworkPlayerChangedTeam.h
  Sail/src/Sail/events/types/NetworkPlayerRequestedTeamChange.h
  Sail/src/Sail/events/types/NetworkUpdateStateLoadStatus.h
  Sail/src/Sail/states/State.cpp
  Sail/src/Sail/states/State.h
  Sail/src/Sail/states/StateIdentifiers.h
  Sail/src/Sail/utils/SailImGui/WaitingForPlayersWindow.cpp
  Sail/src/Sail/utils/SailImGui/WaitingForPlayersWindow.h
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: currently merging

#519 U144/T617 projectiles in replay
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/PBRTestState.cpp
  Sail/src/Sail/Application.cpp
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/EntityFactory.hpp
  Sail/src/Sail/entities/systems/SystemDeclarations.h
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/KillCamReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/ReceiverBase.cpp
  Sail/src/Sail/entities/systems/network/receivers/ReceiverBase.h
  Sail/src/Sail/entities/systems/physics/MovementPostCollisionSystem.cpp
  Sail/src/Sail/entities/systems/physics/MovementPostCollisionSystem.h
  Sail/src/Sail/entities/systems/physics/MovementSystem.cpp
  Sail/src/Sail/entities/systems/physics/MovementSystem.h
  Sail/src/Sail/entities/systems/render/MetaballSubmitSystem.cpp
  Sail/src/Sail/entities/systems/render/MetaballSubmitSystem.h
  Sail/src/Sail/entities/systems/render/ModelSubmitSystem.cpp
Labels: currently merging

#501 HF/SpawnLocationOnSmallMaps
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/entities/systems/Audio/AudioSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.cpp
  Sail/src/Sail/entities/systems/light/SpotLightSystem.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: currently merging

#556 Issue/545
  Sail/src/Sail/utils/GameDataTracker.cpp
Labels: hotfix

#552 Issue/533 Sanity
  Sail/src/Sail/entities/EntityFactory.cpp
Labels: hotfix, needs testing

#565 Fixed intermittent sound crashes
  Sail/src/API/Audio/AudioEngine.cpp
Labels: needs testing

#540 Reworked how meshindex is used in shaderpipeline and renderers
  Sail/src/API/DX12/DX12API.cpp
  Sail/src/API/DX12/DX12ComputeShaderDispatcher.cpp
  Sail/src/API/DX12/DX12ComputeShaderDispatcher.h
  Sail/src/API/DX12/DX12Mesh.cpp
  Sail/src/API/DX12/DX12Mesh.h
  Sail/src/API/DX12/dxr/DXRBase.cpp
  Sail/src/API/DX12/renderer/DX12ForwardRenderer.cpp
  Sail/src/API/DX12/renderer/DX12GBufferRenderer.cpp
  Sail/src/API/DX12/renderer/DX12ParticleRenderer.cpp
  Sail/src/API/DX12/renderer/DX12Renderers.cpp
  Sail/src/API/DX12/renderer/DX12ScreenSpaceRenderer.cpp
  Sail/src/API/DX12/resources/DX12Texture.cpp
  Sail/src/API/DX12/resources/DX12Texture.h
  Sail/src/API/DX12/shader/DX12ShaderPipeline.cpp
  Sail/src/API/DX12/shader/DX12ShaderPipeline.h
  Sail/src/API/DX12/shader/DX12StructuredBuffer.cpp
  Sail/src/API/DX12/shader/DX12StructuredBuffer.h
  Sail/src/Sail/api/ComputeShaderDispatcher.h
  Sail/src/Sail/api/Renderer.cpp
  Sail/src/Sail/api/Renderer.h
  Sail/src/Sail/api/shader/ShaderPipeline.cpp
  Sail/src/Sail/api/shader/ShaderPipeline.h
  Sail/src/Sail/api/shader/StructuredBuffer.h
  Sail/src/Sail/entities/components/ParticleEmitterComponent.cpp
  Sail/src/Sail/entities/systems/Graphics/AnimationSystem.cpp
  Sail/src/Sail/events/Event.h
  Sail/src/Sail/events/Events.h
  Sail/src/Sail/events/types/NewFrameEvent.h
  Sail/src/Sail/graphics/postprocessing/PostProcessPipeline.cpp
Labels: currently merging, needs testing

#569 U621/t630 chat inpout
  SPLASH/src/game/events/TextInputEvent.h
  SPLASH/src/game/states/LobbyClientState.cpp
  SPLASH/src/game/states/LobbyClientState.h
  SPLASH/src/game/states/LobbyHostState.cpp
  SPLASH/src/game/states/LobbyHostState.h
  SPLASH/src/game/states/LobbyState.cpp
  SPLASH/src/game/states/LobbyState.h
  Sail/src/Network/NWrapperClient.cpp
  Sail/src/Sail/KeyBinds.cpp
  Sail/src/Sail/events/Event.h
Labels: currently merging

#567 U628/t654 resource ram
  Sail/src/Sail/api/Mesh.cpp
  Sail/src/Sail/api/Mesh.h
  Sail/src/Sail/graphics/geometry/Animation.cpp
  Sail/src/Sail/graphics/geometry/Animation.h
  Sail/src/Sail/graphics/geometry/Model.cpp
  Sail/src/Sail/graphics/geometry/Model.h
  Sail/src/Sail/resources/AudioData.cpp
  Sail/src/Sail/resources/AudioData.h
  Sail/src/Sail/resources/ParsedScene.cpp
  Sail/src/Sail/resources/ParsedScene.h
  Sail/src/Sail/resources/ResourceManager.cpp
  Sail/src/Sail/resources/ResourceManager.h
  Sail/src/Sail/resources/TextureData.cpp
  Sail/src/Sail/resources/TextureData.h
  Sail/src/Sail/utils/SailImGui/Profiler.cpp
  Sail/src/Sail/utils/SailImGui/Profiler.h
Labels: changes requested, currently merging

#573 Hf/dynamic water grid size
  SPLASH/res/shaders/dxr/Basic.hlsl
  SPLASH/res/shaders/dxr/Common_hlsl_cpp.hlsl
  SPLASH/res/shaders/dxr/PBR.hlsl
  SPLASH/res/shaders/dxr/Shading.hlsl
  SPLASH/res/shaders/dxr/Utils.hlsl
  SPLASH/src/game/states/GameState.cpp
  Sail/src/API/DX12/dxr/DXRBase.cpp
  Sail/src/API/DX12/dxr/DXRBase.h
  Sail/src/API/DX12/renderer/DX12HybridRaytracerRenderer.cpp
  Sail/src/API/DX12/renderer/DX12HybridRaytracerRenderer.h
  Sail/src/API/DX12/renderer/DX12RaytracingRenderer.cpp
  Sail/src/API/DX12/renderer/DX12RaytracingRenderer.h
  Sail/src/Sail/utils/Utils.cpp
  Sail/src/Sail/utils/Utils.h
Labels: currently merging, needs testing

#574 HF/IncreasedMaxPitch
  Sail/src/Sail/entities/systems/input/GameInputSystem.cpp
Labels: currently merging, needs testing

#575 U536/t640 multiple torch bounding boxes
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/components/Components.h
  Sail/src/Sail/entities/components/RagdollComponent.cpp
  Sail/src/Sail/entities/components/RagdollComponent.h
  Sail/src/Sail/entities/systems/physics/CollisionSystem.cpp
  Sail/src/Sail/entities/systems/physics/UpdateBoundingBoxSystem.cpp
  Sail/src/Sail/entities/systems/physics/UpdateBoundingBoxSystem.h
  Sail/src/Sail/entities/systems/render/BoundingboxSubmitSystem.cpp
Labels: currently merging, needs testing

#583 HF/582 added two clear
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.h
Labels: currently merging

#589 U621/t631 chat output + team colour maintenance
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/LobbyState.cpp
  SPLASH/src/game/states/LobbyState.h
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/components/TeamComponent.h
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.h
Labels: currently merging

#581 U625/T669-ImGuiTextures
  SPLASH/src/game/states/MenuState.cpp
  Sail/src/API/DX12/imgui/DX12ImGuiHandler.cpp
  Sail/src/API/DX12/imgui/DX12ImGuiHandler.h
  Sail/src/Sail/api/ImGuiHandler.h
Labels: currently merging

#585 U628/t659 check audio engine
  Sail/src/Sail/resources/ResourceManager.cpp
  Sail/src/Sail/resources/ResourceManager.h
  Sail/src/Sail/utils/SailImGui/Profiler.cpp
  Sail/src/Sail/utils/SailImGui/Profiler.h
Labels: approved

#590 U628/t656 component sizes
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/entities/ECS.cpp
  Sail/src/Sail/entities/ECS.h
  Sail/src/Sail/entities/components/AiComponent.h
  Sail/src/Sail/entities/components/AnimationComponent.h
  Sail/src/Sail/entities/components/AudioComponent.h
  Sail/src/Sail/entities/components/BoundingBoxComponent.h
  Sail/src/Sail/entities/components/CandleComponent.h
  Sail/src/Sail/entities/components/CollidableComponent.h
  Sail/src/Sail/entities/components/CollisionComponent.h
  Sail/src/Sail/entities/components/CollisionSpheresComponent.h
  Sail/src/Sail/entities/components/Component.h
  Sail/src/Sail/entities/components/CullingComponent.h
  Sail/src/Sail/entities/components/FSMComponent.h
  Sail/src/Sail/entities/components/GUIComponent.h
  Sail/src/Sail/entities/components/GunComponent.h
  Sail/src/Sail/entities/components/LifeTimeComponent.h
  Sail/src/Sail/entities/components/LightComponent.h
  Sail/src/Sail/entities/components/LightListComponent.h
  Sail/src/Sail/entities/components/LocalOwnerComponent.h
  Sail/src/Sail/entities/components/MapComponent.h
  Sail/src/Sail/entities/components/MetaballComponent.h
  Sail/src/Sail/entities/components/ModelComponent.h
  Sail/src/Sail/entities/components/MovementComponent.h
  Sail/src/Sail/entities/components/NetworkReceiverComponent.h
  Sail/src/Sail/entities/components/NetworkSenderComponent.h
  Sail/src/Sail/entities/components/OnlineOwnerComponent.h
  Sail/src/Sail/entities/components/ParticleEmitterComponent.h
  Sail/src/Sail/entities/components/PlayerComponent.h
  Sail/src/Sail/entities/components/ProjectileComponent.h
  Sail/src/Sail/entities/components/RagdollComponent.h
  Sail/src/Sail/entities/components/RealTimeComponent.h
  Sail/src/Sail/entities/components/ReplayComponent.h
  Sail/src/Sail/entities/components/ReplayTransformComponent.h
  Sail/src/Sail/entities/components/SanityComponent.h
  Sail/src/Sail/entities/components/SpectatorComponent.h
  Sail/src/Sail/entities/components/SpeedLimitComponent.h
  Sail/src/Sail/entities/components/SpotlightComponent.h
  Sail/src/Sail/entities/components/SprintingComponent.h
  Sail/src/Sail/entities/components/TeamComponent.h
  Sail/src/Sail/entities/components/TextComponent.h
  Sail/src/Sail/entities/components/ThrowingComponent.h
  Sail/src/Sail/entities/components/TransformComponent.h
  Sail/src/Sail/entities/components/VerticalCylinderComponent.h
  Sail/src/Sail/entities/systems/SystemDeclarations.h
  Sail/src/Sail/entities/systems/Systems.h
  Sail/src/Sail/utils/SailImGui/Profiler.cpp
Labels: currently merging, needs testing

#579 Crosshair and hitdetection implemented with ImGui
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/EntityFactory.hpp
  Sail/src/Sail/entities/components/Components.h
  Sail/src/Sail/entities/components/CrosshairComponent.h
  Sail/src/Sail/entities/systems/Gameplay/ProjectileSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/ProjectileSystem.h
  Sail/src/Sail/entities/systems/Graphics/CrosshairSystem.cpp
  Sail/src/Sail/entities/systems/Graphics/CrosshairSystem.h
  Sail/src/Sail/entities/systems/SystemDeclarations.h
  Sail/src/Sail/entities/systems/Systems.h
  Sail/src/Sail/entities/systems/input/SprintingSystem.cpp
  Sail/src/Sail/entities/systems/input/SprintingSystem.h
  Sail/src/Sail/utils/SailImGui/InGameGui.cpp
  Sail/src/Sail/utils/SailImGui/InGameGui.h
  Sail/src/Sail/utils/SailImGui/OptionsWindow.cpp
  Sail/src/Sail/utils/SailImGui/OptionsWindow.h
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: currently merging, needs testing

#587 U530/T645 identify killing projectile
  Sail/src/Sail/entities/components/CandleComponent.h
  Sail/src/Sail/entities/systems/Audio/AudioSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/ProjectileSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleHealthSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleThrowingSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/KillCamReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/KillCamReceiverSystem.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.h
  Sail/src/Sail/entities/systems/network/receivers/ReceiverBase.cpp
  Sail/src/Sail/entities/systems/network/receivers/ReceiverBase.h
  Sail/src/Sail/events/types/PlayerDiedEvent.h
  Sail/src/Sail/events/types/WaterHitPlayerEvent.h
  Sail/src/Sail/netcode/NetworkedStructs.h
  Sail/src/Sail/utils/SailImGui/KillFeedWindow.cpp
Labels: currently merging, needs testing

#592 Issue#536 spectator crash
  Sail/src/Sail/entities/Entity.h
  Sail/src/Sail/entities/systems/Gameplay/SanitySystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/candles/CandleThrowingSystem.cpp
Labels: currently merging, needs testing

#597 Hf/crosshair tweak
  Sail/src/Sail/utils/SailImGui/InGameGui.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: code review in-progress

#602 HF/kill feed insanity
  Sail/src/Sail/entities/components/CandleComponent.h
  Sail/src/Sail/entities/systems/Gameplay/SanitySystem.cpp
Labels: currently merging

#605 Issue#457 - Shoot through walls
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/entities/systems/Gameplay/GunSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/GunSystem.h
Labels: currently merging, needs testing

#621 Updated hasComponent() and getComponent()
  Sail/src/Sail/entities/Entity.cpp
  Sail/src/Sail/entities/Entity.h
Labels: currently merging

#624 HF/player spawning
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Network/NWrapperSingleton.cpp
  Sail/src/Network/NetworkModule.cpp
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/EntityFactory.hpp
  Sail/src/Sail/entities/systems/Gameplay/ProjectileSystem.cpp
  Sail/src/Sail/entities/systems/network/HostSendToSpectatorSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.cpp
  Sail/src/Sail/entities/systems/network/NetworkSenderSystem.h
  Sail/src/Sail/entities/systems/network/receivers/KillCamReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/KillCamReceiverSystem.h
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.cpp
  Sail/src/Sail/entities/systems/network/receivers/NetworkReceiverSystem.h
  Sail/src/Sail/entities/systems/network/receivers/ReceiverBase.cpp
  Sail/src/Sail/entities/systems/network/receivers/ReceiverBase.h
  Sail/src/Sail/netcode/NetworkedStructs.cpp
  Sail/src/Sail/netcode/NetworkedStructs.h
Labels: currently merging

#615 Issue/535 background color
  SPLASH/res/shaders/dxr/Basic.hlsl
Labels: currently merging, enHANSement, screenshot

#622 U622 endgame/t633 chat
  SPLASH/src/ImGuiWindows/Chat/ChatWindow.cpp
  SPLASH/src/ImGuiWindows/Chat/ChatWindow.h
  SPLASH/src/game/events/NetworkChatEvent.h
  SPLASH/src/game/states/EndGameState.cpp
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/LobbyClientState.cpp
  SPLASH/src/game/states/LobbyClientState.h
  SPLASH/src/game/states/LobbyHostState.cpp
  SPLASH/src/game/states/LobbyHostState.h
  SPLASH/src/game/states/LobbyState.cpp
  SPLASH/src/game/states/LobbyState.h
  Sail/src/API/DX12/resources/DX12Texture.cpp
  Sail/src/Network/NWrapper.h
  Sail/src/Sail/Application.cpp
  Sail/src/Sail/Application.h
  Sail/src/Sail/utils/SailImGui/SailImGuiWindow.cpp
  Sail/src/Sail/utils/SailImGui/SailImGuiWindow.h
Labels: currently merging

#625 Map Presets created, added to menu
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/LobbyState.cpp
  SPLASH/src/game/states/LobbyState.h
  SPLASH/src/game/states/MenuState.cpp
  Sail/src/Network/NWrapperClient.cpp
  Sail/src/Network/NWrapperHost.cpp
  Sail/src/Network/NWrapperHost.h
  Sail/src/Sail/Application.cpp
  Sail/src/Sail/api/ImGuiHandler.cpp
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.cpp
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.h
  Sail/src/Sail/utils/SailImGui/OptionsWindow.cpp
  Sail/src/Sail/utils/SailImGui/OptionsWindow.h
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.h
Labels: currently merging, needs testing

#612 U629/t647 cluster per player remake
  SPLASH/res/shaders/dxr/Basic.hlsl
  SPLASH/res/shaders/dxr/Common_hlsl_cpp.hlsl
  Sail/src/API/DX12/DX12Utils.cpp
  Sail/src/API/DX12/DX12Utils.h
  Sail/src/API/DX12/dxr/DXRBase.cpp
  Sail/src/API/DX12/dxr/DXRBase.h
  Sail/src/API/DX12/dxr/DXRUtils.cpp
  Sail/src/API/DX12/dxr/DXRUtils.h
  Sail/src/API/DX12/renderer/DX12HybridRaytracerRenderer.cpp
  Sail/src/API/DX12/renderer/DX12HybridRaytracerRenderer.h
  Sail/src/API/DX12/renderer/DX12RaytracingRenderer.cpp
  Sail/src/API/DX12/renderer/DX12RaytracingRenderer.h
  Sail/src/Sail/api/Renderer.h
  Sail/src/Sail/entities/EntityFactory.cpp
  Sail/src/Sail/entities/components/MetaballComponent.h
  Sail/src/Sail/entities/components/ParticleEmitterComponent.cpp
  Sail/src/Sail/entities/components/ParticleEmitterComponent.h
  Sail/src/Sail/entities/systems/Graphics/ParticleSystem.cpp
  Sail/src/Sail/entities/systems/Graphics/ParticleSystem.h
  Sail/src/Sail/entities/systems/render/MetaballSubmitSystem.cpp
Labels: currently merging, needs testing, screenshot

#629 Light attenuation tweaks
  SPLASH/res/shaders/dxr/PBR.hlsl
Labels: currently merging, needs testing

#628 Maintenance/settings
  SPLASH/res/shaders/dxr/Basic.hlsl
  Sail/src/API/DX12/dxr/DXRBase.cpp
  Sail/src/Sail/Application.cpp
  Sail/src/Sail/entities/systems/Graphics/CrosshairSystem.cpp
  Sail/src/Sail/utils/SailImGui/OptionsWindow.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: currently merging

#640 Fixed issue with spawning in cloning vats
  Sail/src/Sail/entities/systems/Gameplay/LevelSystem/LevelSystem.cpp
Labels: currently merging, needs testing

#632 Issues/streaming stops after pause [Issue#338]
  SPLASH/res/sounds/death/death_5.wav
  SPLASH/res/sounds/jumping/jump.wav
  SPLASH/res/sounds/miscellaneous/sprinkler.wav
  SPLASH/src/game/states/GameState.cpp
  SPLASH/src/game/states/GameState.h
  Sail/src/API/Audio/AudioEngine.cpp
  Sail/src/API/Audio/AudioEngine.h
  Sail/src/Sail/entities/systems/Audio/AudioData.cpp
  Sail/src/Sail/entities/systems/Audio/AudioSystem.cpp
  Sail/src/Sail/entities/systems/network/HostSendToSpectatorSystem.cpp
  Sail/src/Sail/utils/Storage/SettingStorage.cpp
Labels: currently merging

#639 Hf/fixed waiting for players again
  SPLASH/src/game/states/GameState.cpp
  Sail/src/Sail/entities/systems/Graphics/ParticleSystem.cpp
  Sail/src/Sail/entities/systems/Graphics/ParticleSystem.h
  Sail/src/Sail/entities/systems/network/HostSendToSpectatorSystem.cpp
Labels: needs testing
